In [155]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [156]:

# Load the CSV file
df = pd.read_csv('car_evaluation.csv', header=None)
# pick 400 random samples from the dataset
# df = df.sample(n=400, random_state=42)
df.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [157]:
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Load the CSV file
# df = pd.read_csv('car_evaluation.csv', header=None)
# df.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

# # Encoding categorical data
# label_encoders = {}
# for column in df.columns:
#     le = LabelEncoder()
#     df[column] = le.fit_transform(df[column])
#     label_encoders[column] = le

# # Calculate the correlation matrix
# correlation_matrix = df.corr()

# # Plotting the correlation matrix
# plt.figure(figsize=(10, 8))
# sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm')
# plt.title('Correlation Matrix')
# plt.show()

# # Select the top 4 features based on absolute correlation values with the target
# top_features = correlation_matrix['class'].abs().sort_values(ascending=False)[1:5]  # Exclude 'class' itself
# print("Top 4 features selected based on correlation:", top_features.index.tolist())

In [158]:
# df = df[top_features.index.tolist() + ["class"]]

In [159]:
df

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [160]:

# Encoding categorical data
label_encoders = {}

In [161]:
df

     buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [162]:

for column in df.columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

In [163]:

# Splitting the dataset into training and testing sets
X = df.drop('class', axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [164]:

# Creating and training the model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [165]:

# Making predictions
y_pred = model.predict(X_test)

In [166]:

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9739884393063584

In [167]:
df

# take 2 samples from the dataset for each class
df_sample = df.groupby('class').apply(lambda x: x.sample(2)).reset_index(drop=True)
# Splitting the dataset into training and testing sets
X_sample = df_sample.drop('class', axis=1)
y_sample = df_sample['class']
X_train_sample, X_test_sample, y_train_sample, y_test_sample = train_test_split(X_sample, y_sample, test_size=0.2, random_state=42)

In [170]:
df

      buying  maint  doors  persons  lug_boot  safety  class
0          3      3      0        0         2       1      2
1          3      3      0        0         2       2      2
2          3      3      0        0         2       0      2
3          3      3      0        0         1       1      2
4          3      3      0        0         1       2      2
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      3        2         1       2      1
1724       1      1      3        2         1       0      3
1725       1      1      3        2         0       1      2
1726       1      1      3        2         0       2      1
1727       1      1      3        2         0       0      3

[1728 rows x 7 columns]

In [168]:
# dump data to the disk as 
# {
#   "TrainingData": {
#     "Features": [
#       []
#     ],
#     "Labels": []
#   },
#   "ValidationData": {
#     "Features": [
#       []
#     ],
#     "Labels": []
#   }
# }

import json

# convert X_train to double
X_train = X_train.astype(float)
X_test = X_test.astype(float)

training_data = {
    "Features": X_train.values.tolist(),
    "Labels": y_train.values.tolist()
}

validation_data = {
    "Features": X_test.values.tolist(),
    "Labels": y_test.values.tolist()
}

data = {
    "TrainingData": training_data,
    "ValidationData": validation_data
}

with open('train_test_split.json', 'w') as f:
    json.dump(data, f)

In [169]:
y_train.unique()

array([2, 0, 3, 1])

In [46]:
## take 2 samples from each class
df

      buying  maint  doors  persons  lug_boot  safety  class
0          3      3      0        0         2       1      2
1          3      3      0        0         2       2      2
2          3      3      0        0         2       0      2
3          3      3      0        0         1       1      2
4          3      3      0        0         1       2      2
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      3        2         1       2      1
1724       1      1      3        2         1       0      3
1725       1      1      3        2         0       1      2
1726       1      1      3        2         0       2      1
1727       1      1      3        2         0       0      3

[1728 rows x 7 columns]

In [47]:
import json

# convert X_train to double
X_train = X_train.astype(float)[:400]
X_test = X_test.astype(float)[:400]
y_train = y_train[:400]
y_test = y_test[:400]

training_data = {
    "Features": X_train.values.tolist(),
    "Labels": y_train.values.tolist()
}

validation_data = {
    "Features": X_test.values.tolist(),
    "Labels": y_test.values.tolist()
}

data = {
    "TrainingData": training_data,
    "ValidationData": validation_data
}

with open('train_test_split.json', 'w') as f:
    json.dump(data, f)

In [32]:
df_sample = df.groupby('class').apply(lambda x: x.sample(2)).reset_index(drop=True)

In [33]:
df_sample

   buying  maint  doors  persons  lug_boot  safety  class
0       0      2      2        2         2       0      0
1       3      1      3        1         0       2      0
2       1      1      2        1         2       0      1
3       2      1      0        2         0       2      1
4       3      0      1        2         0       0      2
5       2      0      3        0         1       0      2
6       2      2      2        1         0       0      3
7       1      1      2        2         0       0      3

In [16]:
df

# take 2 samples from the dataset for each class
df_sample = df.groupby('class').apply(lambda x: x.sample(2)).reset_index(drop=True)
# Splitting the dataset into training and testing sets
X_sample = df_sample.drop('class', axis=1)
y_sample = df_sample['class']
X_train_sample, X_test_sample, y_train_sample, y_test_sample = train_test_split(X_sample, y_sample, test_size=0.2, random_state=42)

In [17]:
X_train_sample, X_test_sample, y_train_sample, y_test_sample

(   buying  maint  doors  persons  lug_boot  safety
 0       0      2      0        1         0       2
 7       1      0      3        1         0       0
 2       1      2      2        2         2       0
 4       1      3      1        1         1       2
 3       1      2      2        1         2       0
 6       2      1      3        2         0       0,
    buying  maint  doors  persons  lug_boot  safety
 1       2      3      0        1         0       0
 5       2      1      3        0         2       1,
 0    0
 7    3
 2    1
 4    2
 3    1
 6    3
 Name: class, dtype: int64,
 1    0
 5    2
 Name: class, dtype: int64)

In [18]:
import json

# convert X_train_sample to double
X_train_sample = X_train_sample.astype(float)[:40]
X_test_sample = X_test_sample.astype(float)[:40]
y_train_sample = y_train_sample[:40]
y_test_sample = y_test_sample[:40]

training_data = {
    "Features": X_train_sample.values.tolist(),
    "Labels": y_train_sample.values.tolist()
}

validation_data = {
    "Features": X_test_sample.values.tolist(),
    "Labels": y_test_sample.values.tolist()
}

data = {
    "TrainingData": training_data,
    "ValidationData": validation_data
}

with open('train_test_split.json', 'w') as f:
    json.dump(data, f)

In [85]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# Load your dataset
data = pd.read_csv('car_evaluation.csv')

# Assuming the last column is the target and the rest are features
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Logistic Regression model
model = LogisticRegression(multi_class='ovr', solver='liblinear')

# Train the model
model.fit(X_train, y_train)

# Make predictions
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy:.2f}')

ValueError: could not convert string to float: 'vhigh'